spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: challenge
  datasource:
    url: jdbc:sqlite:mydatabase.db
    driver-class-name: org.sqlite.JDBC